### ISSUE TITLE
Q: Can/should I use multiple ebitenui.UIs to represent each UI screen in my game?

### ISSUE THREAD

**Issue by TheMightyGit** [ebitenui/ebitenui#1]
Hi,

I'm just trying out ebitenui and had a question. I have different UIs on different screens and I'm not sure if each screen should be their own separate `ebitenui.UI`s or if they should all be structured to be within a single `ebitenui.UI`?

Thank you <3

**Comment by blizzy78** [comment]
No you just use a single UI for everything. You can either add/remove Containers from the UI, or you can use a FlipBook to switch between different pages (FlipBook.SetPage). You can also use instances of Window, but you will have to set their positions manually which may not be desirable. Check out `cmd/demo` for usage.

That said, I might change it in the future so that multiple instances of UI are possible, but it really shouldn't be necessary to ever use more than one.

**Comment by TheMightyGit** [comment]
That's exactly the info I needed, thank you :)
